### PR TITLE
added french translation

### PR DESCRIPTION
**Pull request by Proxiweb**

### CODE REVIEW

**Comment by TbLtzk** [comment]
Hey chouette! C'était vite!
You were even slightly too fast for me, now. I'm going to put the google play store entries into an .md file in order to be translated as well. So if you have time for translating that one as well, I will be glad to accept another PR.

**Comment by TbLtzk** [comment]
Did you try this in the browser or on a device?
Just asking to assert texts are not too long for where they are displayed.

**Comment by TbLtzk** [comment]
Are you on slack? You might  consider joining
https://stellar-public.slack.com

**Comment by jedmccaleb** [comment]
Got to go through this url: http://slack.stellar.org/

**Comment by TbLtzk** [comment]
The additional resources for translation are [online](../tree/master/www/i18n/additional) now.

**Pull request merged**
