### PR TITLE
Fix mailto: url and explicit setting of allowed intents.

### LINKED ISSUE #54: mailto does not work on device
In the about view, section 'Contact' there is a mailto:centaurus@xcoins.de link. It works in the ripple emulator but not on my android device (Galaxy Tab 4).
Did not try other emulators or platforms yet.

### PR DESCRIPTION
**Pull request by raymens**
Fixes #54

### CODE REVIEW

**Comment by TbLtzk** [comment]
Hey you're really fast! I'll do my best to test your changes on the device soon and pull this request.
But I have no doubt it will work ;)

**Comment by raymens** [comment]
I did receive a notice of something when I clicked the link, but I think that's related to the fact that the emulator has no email client.

**Comment by TbLtzk** [comment]
Which emulator did you use? In the integrated ripple android emulator it opens the host system's default mail client.

**Comment by raymens** [comment]
VS Android Emulator. I think that the Ripple just ignores the emulation part and sends that link direct to the browser, which will by default open the host system's default mail client and thus will always work. Even when it shouldn't, due to permissions like now. Since cordova-cli 4.0 it's required to use permissions (AFAIK).

**Comment by TbLtzk** [comment]
I tried this but it does not solve the problem. The link remains dead. No cordova log, nothing on the js console. Nevertheless your commit looks reasonable, just remember to include new plugins also in 
https://github.com/TbLtzk/Centaurus/blob/master/hooks/after_platform_add/010_install_plugins.js

**Comment by raymens** [comment]
That's weird. As the message I get in the emulator is the same as the one mentioned in http://stackoverflow.com/questions/9834456/is-this-code-correct-send-email-via-android where the answer is:
*Because you have no email application installed in your device. Working with this code, you must have email applications installed in your phone.*

**Comment by TbLtzk** [comment]
No, I found the solution:
`<access origin="mailto:*" launch-external="yes"/>` this one will do it. I just wonder whether the plugin is needed then

**Comment by raymens** [comment]
That's what I had before I installed the plugin. Might be related to Android version? What version are you running?

**Comment by TbLtzk** [comment]
my device is a lollipop. But I have a guess now. I'm not using the latest cordova android platform but rather `cordova platform add android@3.7.1` had a lot of issues otherwise but again might be because im not so experienced

**Comment by TbLtzk** [comment]
did the mailto not work for you without the plugin?

**Comment by raymens** [comment]
It seems to work, I get the same message, so that might be a better (simpler) solution :)

**Pull request closed without merging**
