### PR TITLE
add japanese translate

### PR DESCRIPTION
**Pull request by you21979**
I've translated strings into Japanese. Please merge it.

### CODE REVIEW

**Comment by TbLtzk** [comment]
Awesome, thx a lot!

**Comment by TbLtzk** [comment]
some keys are not translated. This might have been intended for some of them, but for some this seems to be a mistake
```
{
  "controllers.receive.share.p2": "Centaurus - Stellar Wallet for Android!",
  "controllers.receive.share.title": "My Stellar Address",
  "controllers.wallet.shareKeys.message.caption": "My Stellar Keys",
  "general.btn.cancel": "Cancel",
  "general.btn.import": "Import",
  "general.btn.ok": "Ok",
  "navigation.about.title": "About",
  "tabs.about.main.divider": "Centaurus Stellar Wallet",
  "tabs.about.title": "Centaurus",
  "tabs.send.btn.destinationTag": "Destination Tag",
  "tabs.trx.from": "from",
  "tabs.trx.to": "to",
}

```

**Comment by TbLtzk** [comment]
image

**Comment by you21979** [comment]
Thank you Merge.
"About" is better not to translate.

**Pull request merged**
