### PR TITLE
added moments field to transaction llist

### PR DESCRIPTION
**Pull request by agyepong**
need to add moment.js library.
I placed it in /lib/moment.js
[moments.zip](https://github.com/TbLtzk/Centaurus/files/67641/moments.zip)

### CODE REVIEW

**Comment by TbLtzk** [comment]
I cannot pull your changes like that. pls pull the head of my master branch first, and merge with your changes.
image

**Comment by agyepong** [comment]
pull request to merge moment changes

**Comment by agyepong** [comment]
It is not obvious from Visual Studio how to pull the head of your master
branch and merge it with my changes. I am looking around to see how to do
that. I can use any help.

Thanks

**Comment by jedmccaleb** [comment]
You shouldn't try from within visual studio. I'd use tortisegit if you are on windows.

**Comment by agyepong** [comment]
I will try that.

Thanks

**Comment by agyepong** [comment]
It appears rebase will do the trick

https://git-scm.com/docs/git-rebase

I see this in visual studio

Thanks

[image: Inline image 1]

**Comment by agyepong** [comment]
I am able to merge using tortoisegit.
Now, my build dont work. I have the following issues.

Thanks

[image: Inline image 1]

**Comment by TbLtzk** [comment]
I cannot see your images. Can you post the error output of the build?
In VS try a right click on `Dependencies` and `Restore Packages`
Does the project run in ripple android emulator (or browser)?

**Comment by agyepong** [comment]
I right click on Dependencies and Restore Packages but this did not help
I am using ripple android emulator
I re-did the merge and now I have the issues below:

jquery doc ready
contentscript.js:429 document.readyState = complete
opbhoeventhandler.js:95 command =PromptUILoaded
==>fidikogfgleiaefnjbmnjaplmgknppkg
opbhoeventhandler.js:163 promptui is loaded so lets processpage now1
fidikogfgleiaefnjbmnjaplmgknppkg
opbhoeventhandler.js:165 promptui is loaded so lets processpage now2
fidikogfgleiaefnjbmnjaplmgknppkg
contentscriptcomm.js:41 PromptUILoaded
contentscript.js:394 checkpage =
http://localhost:4400/index.html?enableripple=cordova-3.0.0-NexusGalaxy
_webusridFlg=true _passFlg=false
contentscript.js:394 checkpage =
http://localhost:4400/index.html?enableripple=cordova-3.0.0-NexusGalaxy
_webusridFlg=true _passFlg=false
ripple.js:50 Synchronous XMLHttpRequest on the main thread is deprecated
because of its detrimental effects to the end user's experience. For more
help, check http://xhr.spec.whatwg.org/.
ripple.js:50 GET http://localhost:4400/config.xml 404 (Not Found)(anonymous
function) @ ripple.js:50module.exports.initialize @ ripple.js:50_baton.pass
@ ripple.js:13xhr.onreadystatechange @ ripple.js:39
ripple.js:37 cordova :: Initialization Finished (Make it so.)
index.html:31 GET http://localhost:4400/lib/moment.js
ionic.bundle.js:21162 pascalprecht.translate.$translateSanitization: No
sanitization strategy has been configured. This can have serious security
implications. See
http://angular-translate.github.io/docs/#/guide/19_security for details.
stellar-sdk.js:2131 AccountCallBuilder#address is deprecated, please use
AccountCallBuilder#accountId instead
ripple.js:50 GET
http://localhost:4400/ripple/xhr_proxy?tinyhippos_apikey=ABC&tinyhippos_rur…7OVSGMCHU4EFDIWNTOACM6AZVGP6RPJX5L67NVSCOPI4WR6CP%3Fc%3D0.6001441944390535
404 (Not Found)(anonymous function) @ ripple.js:50xhrAdapter @
stellar-sdk.js:6084(anonymous function) @
stellar-sdk.js:5951lib$es6$promise$$internal$$initializePromise @
stellar-sdk.js:978lib$es6$promise$promise$$Promise @
stellar-sdk.js:1269dispatchRequest @
stellar-sdk.js:5947lib$es6$promise$$internal$$tryCatch @
stellar-sdk.js:931lib$es6$promise$$internal$$invokeCallback @
stellar-sdk.js:943(anonymous function) @
stellar-sdk.js:1491lib$es6$promise$asap$$flush @ stellar-sdk.js:725
services.js:58 account not found
ripple.js:50 GET
http://localhost:4400/ripple/xhr_proxy?tinyhippos_apikey=ABC&tinyhippos_rur…NVSCOPI4WR6CP/effects%3Flimit%3D30%26order%3Ddesc%26c%3D0.6303875197190791
404 (Not Found)(anonymous function) @ ripple.js:50xhrAdapter @
stellar-sdk.js:6084(anonymous function) @
stellar-sdk.js:5951lib$es6$promise$$internal$$initializePromise @
stellar-sdk.js:978lib$es6$promise$promise$$Promise @
stellar-sdk.js:1269dispatchRequest @
stellar-sdk.js:5947lib$es6$promise$$internal$$tryCatch @
stellar-sdk.js:931lib$es6$promise$$internal$$invokeCallback @
stellar-sdk.js:943(anonymous function) @
stellar-sdk.js:1491lib$es6$promise$asap$$flush @ stellar-sdk.js:725
services.js:175 open effects stream with cursor: now
services.js:201 newError {name: "NotFoundError", message: Object, data:
Object}
ripple.js:40 missing exec:Keyboard.init
ripple.js:40 []
ripple.js:40 TypeError: Cannot read property 'init' of undefined(…)
ripple.js:40 TypeError: Cannot read property 'init' of undefined
    at module.exports.exec (ripple.js:40)
    at null.<anonymous> (keyboard.js:36)
    at Channel.fire (cordova.js:816)
    at cordova.js:1277
    at f (cordova.js:688)
    at Channel.fire (cordova.js:816)
    at cordova.js:1264
    at onScriptLoadingComplete (cordova.js:1730)
    at scriptLoadedCallback (cordova.js:1747)
    at HTMLScriptElement.<anonymous> (cordova.js:1701)
ripple.js:48 Keyboard
ripple.js:48 init
contentscript.js:428 jquery doc ready
contentscript.js:429 document.readyState = complete
ripple.js:37 cordova :: Native back button handler was detached.
ripple.js:40 missing exec:Keyboard.hideKeyboardAccessoryBar
ripple.js:40 [true]
ripple.js:40 TypeError: Cannot read property 'hideKeyboardAccessoryBar' of
undefined(…)
ripple.js:40 TypeError: Cannot read property 'hideKeyboardAccessoryBar' of
undefined
    at module.exports.exec (ripple.js:40)
    at Function.Keyboard.hideKeyboardAccessoryBar (keyboard.js:12)
    at app.js:14
    at Array.<anonymous> (ionic.bundle.js:48817)
    at onPlatformReady (ionic.bundle.js:2452)
    at Channel.fire (cordova.js:816)
    at cordova.js:224
ripple.js:48 Keyboard
ripple.js:48 hideKeyboardAccessoryBar


I also tried the following but they did not help

GitHub> cd C:\GitHub\Centaurus\
C:\GitHub\Centaurus [master +0 ~1 -0]> npm install
npm WARN EPACKAGEJSON Centaurus@0.1.0 No repository field.
npm WARN EPACKAGEJSON Centaurus@0.1.0 No license field.

C:\GitHub\Centaurus [master +0 ~1 -0]> bower install
bower angular-animate extra-resolution Unnecessary resolution:
angular-animate#1.4.3
bower angular-sanitize extra-resolution Unnecessary resolution:
angular-sanitize#1.4.3
bower angular-ui-router extra-resolution Unnecessary resolution:
angular-ui-router#0.2.13
C:\GitHub\Centaurus [master +0 ~1 -0]>

**Comment by TbLtzk** [comment]
Your code seems to be almost ok (as far as it is pushed to github master). When I clone and run it I get
image
The according error is:
```
ReferenceError: moment is not defined
    at momentsFilter (http://localhost:4400/js/filters/filters.js:7:25)
    at fn (eval at <anonymous> (http://localhost:4400/lib/ionic/release/js/ionic.bundle.js:21977:15), <anonymous>:4:205)
    at regularInterceptedExpression (http://localhost:4400/lib/ionic/release/js/ionic.bundle.js:23059:21)
    at Object.expressionInputWatch [as get] (http://localhost:4400/lib/ionic/release/js/ionic.bundle.js:22961:26)
    at Scope.$digest (http://localhost:4400/lib/ionic/release/js/ionic.bundle.js:24507:40)
    at http://localhost:4400/lib/ionic/release/js/ionic.bundle.js:24717:26
    at completeOutstandingRequest (http://localhost:4400/lib/ionic/release/js/ionic.bundle.js:14226:10)
    at http://localhost:4400/lib/ionic/release/js/ionic.bundle.js:14498:7
```

**Comment by agyepong** [comment]
It needs the moment+locale.js library. I added moment to  bower.json. how do we fix this.  Thanks 


Sent from my Samsung device

-------- Original message --------

**Comment by TbLtzk** [comment]
As this works on your machine (or used to work) there must be some of your local changes missing in your commit. Is there a separate bower package for locale.js? If so, don't we need an include in the index.html?

**Comment by TbLtzk** [comment]
maybe the moment bower package only works in node:
```                require('./locale/' + name);```
Maybe we need to browserify moment.js or maybe there is just another bower package for that purpose. Can you rename your local moment.js, get it again via bower (restore packages in VS) and compare both with a diff tool? Are they identical?

**Comment by agyepong** [comment]
no there is no separate locale.js.

locales are in: \www\lib\moment\locale
after Dependencies --> Restore Packages or
$ bower install moment --save
Thanks

**Comment by agyepong** [comment]
The problem was this line in bower.json
<script src="lib/moment.js"></script>

It has been fixed
<script src="lib/moment/moment.js"></script>

bower install puts moment at /lib/moment not /lib

Thanks

**Comment by agyepong** [comment]
I have things right now but is getting this errors, any ideas?

Severity Code Description Project File Line Suppression State
Error TS2304 Cannot find name 'IServiceProvider'. Centaurus
C:\GitHub\Centaurus\www\lib\angular-ui-router\api\angular-ui-router.d.ts 31
Active

Severity Code Description Project File Line Suppression State
Error TS2304 Cannot find name 'IServiceProvider'. Centaurus
C:\GitHub\Centaurus\www\lib\angular-ui-router\api\angular-ui-router.d.ts 49
Active

Severity Code Description Project File Line Suppression State
Error TS2304 Cannot find name 'IPromise'. Centaurus
C:\GitHub\Centaurus\www\lib\angular-ui-router\api\angular-ui-router.d.ts 82
Active

Severity Code Description Project File Line Suppression State
Error 'MySQL' is not recognized as an internal or external command,
Centaurus C:\Program Files
(x86)\MSBuild\Microsoft\VisualStudio\v14.0\ApacheCordovaTools\vs-mda-targets\Microsoft.MDA.FileMirroring.targets
287

Severity Code Description Project File Line Suppression State
Error operable program or batch file. Centaurus C:\Program Files
(x86)\MSBuild\Microsoft\VisualStudio\v14.0\ApacheCordovaTools\vs-mda-targets\Microsoft.MDA.FileMirroring.targets
287

Severity Code Description Project File Line Suppression State
Error 'MySQL' is not recognized as an internal or external command,
Centaurus C:\Program Files
(x86)\MSBuild\Microsoft\VisualStudio\v14.0\ApacheCordovaTools\vs-mda-targets\Microsoft.MDA.FileMirroring.targets
287

Severity Code Description Project File Line Suppression State
Error operable program or batch file. Centaurus C:\Program Files
(x86)\MSBuild\Microsoft\VisualStudio\v14.0\ApacheCordovaTools\vs-mda-targets\Microsoft.MDA.FileMirroring.targets
287

Severity Code Description Project File Line Suppression State
Error EPERM, operation not permitted
'C:\GitHub\Centaurus\platforms\android\assets\www\plugins\cordova-plugin-file\www\fileSystems.js'
Centaurus C:\GitHub\Centaurus\MDAVSCLI 1

Thanks

**Comment by TbLtzk** [comment]
it works on my machine now! Just it does not apply the selected language. It is always english.

You might try to switch to an older version of the android platform. I added a description here:
https://github.com/TbLtzk/Centaurus/blob/master/README.md#advanced-android

Also note there have been changes to the `configTemplate.xml`. You may need to apply those to your local copy `config.xml` as well.

**Comment by agyepong** [comment]
I need to modify the filter to use the selected language. how do you get and set language? Thanks 


Sent from my Samsung device

-------- Original message --------

**Comment by TbLtzk** [comment]
Look at the controller of the about view. Or any commits attached to issue #11Versendet mit der SolMail-App--------- Original Message ---------
From: agyepong 
To: TbLtzk/Centaurus 
Date: Thu Dec 24 12:48:08 MEZ 2015
Subject: Re: [Centaurus] added moments field to transaction llist (#56)


    
I need to modify the filter to use the selected language. how do you get and set language? Thanks 


Sent from my Samsung device

-------- Original message --------

**Comment by agyepong** [comment]
There are 2 items to note:
1. the language experts would need to modify ./lib/moment/locale files to fit the moment field on the transaction page. I didn't want to arbitrary truncate at a point where it does not make sense.
2. when the transactions button is clicked the transaction controller is not called, if transactions data has not changed. this means sometimes the locale may be different from the displayed transactions. this may not be a problem because users are not going to be changing the locale in between transactions

**Comment by agyepong** [comment]
I see my changes are merged now.
is there something you want me to work on?

Thanks

**Comment by TbLtzk** [comment]
There's still one issue I realized just after merging. If you change the language, the moments locale does not change alike. You have to quit the app and reopen, then it shows in the new language.
Not a severe problem, because I don't expect users to change language all the time. But if you find an easy solution to that it would be nice.
And please check my new layout. It better adapts to different screen sizes and orientation.
Have a nice new year's eve.

**Pull request merged**
