### PR TITLE
Dutch language

### PR DESCRIPTION
**Pull request by raymens**
Tested this on the VS Android emulator.

### CODE REVIEW

**Comment by TbLtzk** [comment]
Hey cool, thanks a lot raymens!

**Comment by TbLtzk** [comment]
You were even slightly too fast for me, now. I'm going to put the googe play store entries into an .md file in order to be translated as well. So if you have time for translating that one as well, I will be glad to accept another PR.

**Comment by raymens** [comment]
Yeah sure, I can probably do that within a few days. Not sure if I have the time this weekend.

**Comment by TbLtzk** [comment]
Great! And no hurry. Think It won't be public on google play within less than 2 weeks! The additional resources for translation are [online](../tree/master/www/i18n/additional) now.

**Pull request merged**
