### PR TITLE
enabling sending other assets than XLM

### PR DESCRIPTION
**Pull request by dchrist22**
A transaction with an asset other than XLM can now be created.

### CODE REVIEW

**Comment by dchrist22** [comment]
making new merge request soon, need to do reformatting

**Comment by TbLtzk** [comment]
Frankly this is not the direction I want to go. 
As soon as we are dealing with non native assets I would always use a path payment, which happens to be a different operation.

**Comment by TbLtzk** [comment]
Try if you get alternatives, when you enable this line:
https://github.com/dchrist22/Centaurus/blob/f054a43828dc70d14e973dfd4f209606171af221/www/js/controllers/controllers.send.js#L94

**Comment by dchrist22** [comment]
Are the path payments meant to be used for cases like: USD -> XLM -> USD. So that the sourceAsset and destAsset are always the same?

**Comment by jedmccaleb** [comment]
Path payments are for when the source and dest are different. But it could be USD:G1  -> XML -> USD:G2  where G1 and G2 are two different gateways

**Pull request closed without merging**
